modules/thunder_media/config/install/thunder_media.configuration.yml
modules/thunder_media/src/Form/ConfigurationForm.php
modules/thunder_media/thunder_media.info.yml
modules/thunder_media/thunder_media.links.menu.yml
modules/thunder_media/thunder_media.module
modules/thunder_media/thunder_media.routing.yml

After having some issues with dirty image filenames, we want to clean filenames before uploading. @Cyberschorsch, @IT-Cru and @dbosen please review if this would fit for your needs.

Clean filenames before uploading

---

modules/thunder_media/config/install/core.entity_form_display.media.instagram.default.yml
modules/thunder_media/config/install/core.entity_form_display.media.twitter.default.yml
modules/thunder_media/config/install/field.field.media.instagram.field_url.yml
modules/thunder_media/config/install/field.field.media.twitter.field_url.yml
modules/thunder_media/thunder_media.module
modules/thunder_paragraphs/config/install/field.field.paragraph.link.field_link.yml
tests/src/FunctionalJavascript/ArticleCreationTest.php
tests/src/FunctionalJavascript/ThunderParagraphsTestTrait.php

- Hide "Media name" in instagram and twitter form. Its not needed anymore. Media Entity can specify default names
- Readd "Add media" button to media view
- Make Url required in link paragraph

Minor fixes

---

modules/thunder_media/config/install/core.entity_view_display.media.instagram.thumbnail.yml
modules/thunder_media/thunder_media.install
modules/thunder_paragraphs/config/install/core.entity_view_display.paragraph.instagram.preview.yml
thunder.install

Adjusted few update hooks that failed on update testing.
Also adjusted configuration files with "_core.default_config_hash".

Adjusted few update hooks that could fail

---

modules/thunder_article/modules/thunder_fia/config/install/core.entity_view_display.media.video.facebook_instant_articles_rss.yml

he following extensions will be enabled: thunder_fia, fb_instant_articles
Do you really want to continue? (y/n): y
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects (core.entity_view_display.media.video.facebook_instant_articles_rss)     [error]
provided by thunder_fia have unmet dependencies' in /Users/christianfritsch/repositories/thunder/thunder/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:84
Stack trace:
#0 /Users/christianfritsch/repositories/thunder/thunder/core/lib/Drupal/Core/Config/ConfigInstaller.php(460):
Drupal\Core\Config\UnmetDependenciesException::create('thunder_fia', Array)
#1 /Users/christianfritsch/repositories/thunder/thunder/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): …

Thunder FIA throws umnet dependencies

---

modules/thunder_media/config/install/field.field.media.image.field_image.yml
modules/thunder_media/config/install/field.field.media.video.field_media_video_embed_field.yml
modules/thunder_media/thunder_media.install

Set image field as required for Image Media Bundle and set embed video field as required in Video Media Bundle.
+ Update hook to change that configuration for existing fields on system.

Set required fileds for Image and Video bundles.

---

composer.json
config/install/user.role.anonymous.yml
config/install/user.role.authenticated.yml
drupal-org.make
drupal-org.make.yml
thunder.info.yml
thunder.install

Integrate access_unpublished

---

modules/thunder_demo/thunder_demo.info.yml

Enable help module to get an overview of all our tours

---

modules/thunder_media/config/install/views.view.image_browser.yml
modules/thunder_media/config/install/views.view.media_browser.yml
modules/thunder_media/thunder_media.install
modules/thunder_updater/updates.yml

Remove useless filter, add filter to search in galleries

---

themes/thunder_base/css/node-image-field-fix.css
themes/thunder_base/thunder_base.libraries.yml

Fix issue with field image floating in article paragraph

---

modules/thunder_media/thunder_media.install

Added update hook dependencies for Thunder Updater

---

modules/thunder_article/src/ThunderNodeForm.php
modules/thunder_article/thunder_article.module
tests/src/FunctionalJavascript/ArticleCreationTest.php
tests/src/FunctionalJavascript/MediaGalleryModifyTest.php
tests/src/FunctionalJavascript/MediaImageModifyTest.php
tests/src/FunctionalJavascript/MetaInformationTest.php
tests/src/FunctionalJavascript/ThunderJavascriptTestBase.php

Add a save and continue button to the node form

---

modules/thunder_article/thunder_article.info.yml
modules/thunder_updater/src/Updater.php
modules/thunder_updater/thunder_updater.services.yml
modules/thunder_updater/updates.yml
thunder.install

Enable metatag_facebook by default

---

.travis.yml

add develop branch to test branches

---

modules/thunder_article/thunder_article.info.yml
modules/thunder_media/thunder_media.info.yml
modules/thunder_paragraphs/thunder_paragraphs.info.yml
modules/thunder_taxonomy/thunder_taxonomy.info.yml
modules/thunder_updater/updates.yml
thunder.install

Enable config_update by default

---

composer.json

Change thunder_admin path

---

modules/thunder_media/thunder_media.install

Fix update tests

---

modules/thunder_article/src/ThunderNodeForm.php

IEF was not saved, destination parameter breaks button

---

docs/varnish.md

Added documentation for Varnish tag-based cache invalidation

---

docs/development.md

Add docs how to import and update configuration

---

thunder.profile

Adjusted favicon for Infinite theme

---

modules/thunder_demo/thunder_demo.install
modules/thunder_demo/thunder_demo.module

Added whitelist of tours for defualt thunder themes

---

scripts/travis/03-test-source-code.sh

Remove nvm and custom npm

---

modules/thunder_article/modules/thunder_fia/thunder_fia.module
modules/thunder_article/src/Breadcrumb/ThunderArticleBreadcrumbBuilder.php
modules/thunder_article/src/Twig/FilterExtension.php
modules/thunder_media/src/Form/ConfigurationForm.php
modules/thunder_media/src/Plugin/ImageEffect/AutoAspectEffect.php
modules/thunder_media/src/Tests/FilenameTransliterationTest.php
modules/thunder_taxonomy/src/ThunderTermForm.php
src/Installer/Form/ModuleConfigureForm.php
src/Plugin/Block/ThunderPoweredByBlock.php
src/Plugin/Thunder/OptionalModule/AbstractOptionalModule.php
src/Plugin/Thunder/OptionalModule/GoogleAnalytics.php
src/Plugin/Thunder/OptionalModule/Harbourmaster.php
src/Plugin/Thunder/OptionalModule/IvwIntegration.php
src/Plugin/Thunder/OptionalModule/NexxIntegration.php
src/Plugin/Thunder/OptionalModule/RiddleIntegration.php
src/Tests/Installer/ThunderInstallerGermanTest.php
src/Tests/Installer/ThunderInstallerTest.php
src/ThunderUpdateLogger.php
tests/src/FunctionalJavascript/ThunderJavascriptTestBase.php
thunder.install
thunder.profile

fix array syntax

---

modules/thunder_article/modules/thunder_fia/thunder_fia.module
modules/thunder_article/src/Breadcrumb/ThunderArticleBreadcrumbBuilder.php
modules/thunder_article/src/Twig/FilterExtension.php
modules/thunder_media/src/Form/ConfigurationForm.php
modules/thunder_media/src/Plugin/ImageEffect/AutoAspectEffect.php
modules/thunder_media/src/Tests/FilenameTransliterationTest.php
modules/thunder_taxonomy/src/ThunderTermForm.php
modules/thunder_updater/src/Entity/Update.php
modules/thunder_updater/thunder_updater.module
src/Installer/Form/ModuleConfigureForm.php
src/Plugin/Block/ThunderPoweredByBlock.php
src/Plugin/Thunder/OptionalModule/AbstractOptionalModule.php
src/Plugin/Thunder/OptionalModule/GoogleAnalytics.php
src/Plugin/Thunder/OptionalModule/Harbourmaster.php
src/Plugin/Thunder/OptionalModule/IvwIntegration.php
src/Plugin/Thunder/OptionalModule/NexxIntegration.php
src/Plugin/Thunder/OptionalModule/RiddleIntegration.php
src/Tests/Installer/ThunderInstallerGermanTest.php
src/Tests/Installer/ThunderInstallerTest.php
src/ThunderUpdateLogger.php
tests/src/FunctionalJavascript/ThunderJavascriptTestBase.php
thunder.install
thunder.profile

Cherry pick coding styles

---

scripts/travis/03-test-source-code.sh

revert removal

---

modules/thunder_article/thunder_article.install
modules/thunder_media/thunder_media.install
modules/thunder_paragraphs/thunder_paragraphs.install
modules/thunder_updater/src/UpdateLogger.php
modules/thunder_updater/src/Updater.php
modules/thunder_updater/src/UpdaterInterface.php
modules/thunder_updater/thunder_updater.services.yml
thunder.install
thunder.services.yml

Move Logger

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Thunder 1.2

---

modules/thunder_media/config/install/views.view.image_browser.yml
modules/thunder_media/config/install/views.view.video_browser.yml
modules/thunder_media/css/media_entity_browser.view.css
modules/thunder_media/thunder_media.install
modules/thunder_updater/src/Updater.php
modules/thunder_updater/updates.yml

Streamline Entity Browser view

---

modules/thunder_media/thunder_media.install

[TEST_UPDATE=true] Fixed update hook

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Release preparations

---

scripts/travis/04-install-thunder.sh

Adjsuted used project version to use 8.1.x

---

thunder.install

Added update hook to add access_unpublished permissions

---

modules/thunder_media/thunder_media.install
scripts/travis/04-install-thunder.sh
thunder.install

Adjust entity browser texts in update process

---

config/install/user.role.editor.yml
config/install/user.role.seo.yml
tests/src/FunctionalJavascript/Update/ThunderMediaTest.php
thunder.install

Never autoplay videos for seo and editor

---

build-thunder.make
build-thunder.make.yml

update make file to use rc1

---

modules/thunder_liveblog/thunder_liveblog.info.yml

Add missing package information.

---

modules/thunder_article/modules/thunder_riddle/config/install/media_entity.bundle.riddle.yml
modules/thunder_article/modules/thunder_riddle/thunder_riddle.info.yml
thunder.install

Adjusted Riddle integration dependency

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Release information and version bump.

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Release information

---

modules/thunder_article/modules/thunder_fia/thunder_fia.module

2883612 - Fix PHP notice when trying to change the format for the author name.

---

README.md
modules/thunder_article/thunder_article.info.yml
modules/thunder_article/thunder_article.install

make shariff a soft dependency

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml
drupal-org-core.make
drupal-org-core.make.yml

Update drupal core and prepare release

---

build-thunder.make
build-thunder.make.yml

Put branch back into make file

---

build-thunder.make
build-thunder.make.yml
drupal-org-core.make
drupal-org-core.make.yml

Bump drupal core

---

.travis.yml
CHANGELOG.md
build-thunder.make
build-thunder.make.yml
drupal-org-core.make
drupal-org-core.make.yml

update 8.1.x branch

---

modules/thunder_article/thunder_article.install
modules/thunder_media/thunder_media.install
modules/thunder_updater/src/Entity/Update.php
modules/thunder_updater/src/Entity/UpdateInterface.php
modules/thunder_updater/src/UpdateChecklist.php
modules/thunder_updater/src/Updater.php
modules/thunder_updater/src/UpdaterInterface.php
modules/thunder_updater/thunder_updater.info.yml
modules/thunder_updater/thunder_updater.install
modules/thunder_updater/thunder_updater.module
modules/thunder_updater/thunder_updater.services.yml
thunder.install

Checklist soft dependency

---

CHANGELOG.md
tests/src/FunctionalJavascript/MediaGalleryModifyTest.php

Merge master to develop

---

modules/thunder_media/thunder_media.info.yml

I was not able to install current dev on my local machine, because of missing dependencies in thunder_media. This PR fixed it for me

Missing dependencies

---

modules/thunder_media/config/install/media_entity.bundle.twitter.yml
modules/thunder_media/config/update/thunder_media__thunder_update_8112.yml

Do not generate twitter thumbnails

---

scripts/travis/01-setup-environment.sh
scripts/travis/02-before-install.sh

Changed way of installing of imagick

---

README.md
drupal-org-core.make
drupal-org-core.make.yml

Update core make file

---

README.md

fix composer create line

---

README.md
modules/thunder_media/thunder_media.install
modules/thunder_updater/updates.yml

enable empty fields module

---

.github/PULL_REQUEST_TEMPLATE.md

Issue #2899267 by volkerk: Fix link in pull request template

---

modules/thunder_article/modules/thunder_riddle/thunder_riddle.install

Issue #2899661: Cannot reinstall thunder riddle integration

---

.gitignore

Issue #2899899: Ignore package-lock.json in git

---

tests/src/FunctionalJavascript/ModuleIntegrationTest.php
tests/src/FunctionalJavascript/ThunderJavascriptTestBase.php

Fix for scrolling of elements into view

Issue #2900417: Tests are failing with Admin Theme 8.x-2.0-beta4

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Issue #2900587 by daniel.bosen: Prepare release 8.2.6 PR 2/3

---

CHANGELOG.md

Issue #2900587 by daniel.bosen: Prepare release 8.2.6 PR 3/3

---

scripts/travis/04-install-thunder.sh

Issue #2900717: Use thunder admin theme develop branch in distribution tests

---

modules/thunder_paragraphs/thunder_paragraphs.module
tests/src/FunctionalJavascript/Integration/InlineEntityFormTest.php

Issue #2900626: Saving of collapsed paragraphs with referenced fields doesn't work

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Issue #2902844 by daniel.bosen: Release 8.2.7 PR 2 / 3

---

CHANGELOG.md

Issue #2902844 by daniel.bosen: Release 8.2.7 PR 3 / 3

---

modules/thunder_updater/updates.yml

Issue #2905081: Break up checkboxes into releases

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml
tests/src/FunctionalJavascript/ArticleCreationTest.php

Issue #2910836 by mtodor: Release 8.2.8 - PR 2 / 3

---

CHANGELOG.md
tests/src/FunctionalJavascript/ArticleCreationTest.php

Release 8.2.8 PR 3 / 3

---

config/install/simple_sitemap.bundle_settings.node.article.yml
config/install/simple_sitemap.bundle_settings.node.page.yml
config/install/simple_sitemap.bundle_settings.taxonomy_term.channel.yml

Issue #2913792: Cron failing because of simple_sitemap

---

scripts/travis/04-install-thunder.sh

Issue #2914344 by mtodor: Use development Thunder Admin theme for tests

---

CHANGELOG.md
build-thunder.make
build-thunder.make.yml

Issue #2915394 by daniel.bosen: Release 8.2.9 PR2

---

CHANGELOG.md

Issue #2915394 by daniel.bosen: Release 8.2.9 PR3

---

scripts/travis/04-install-thunder.sh

Issue #2915462: Keep drush requirement in tests

---

modules/thunder_updater/updates.yml
thunder.info.yml
thunder.install

Issue #2915435: Integrate inline form errors

---

modules/thunder_demo/content/crop/6d04fa9e-ace9-4f89-ac32-8ca14ec18719.json
modules/thunder_demo/content/file/372a6e28-de43-491d-9e6f-ee0e93747879.json
modules/thunder_demo/content/file/9e4f6c4c-3631-43aa-9ad7-1fb939dbb1dd.json
src/Tests/Installer/ThunderInstallerTest.php

Issue #2915688: Demo content not installable in german language

---

drupal-org-core.make
tests/src/FunctionalJavascript/ModuleIntegrationTest.php

Issue #2920808: Update Thunder to Drupal 8.4.2

---

CHANGELOG.md
build-thunder.make

Release task 2
"Create release branch from master, create two commits, one to bump version in build-thunder.make files and a second one to write the changelog. Merge back into master without squashing. Now tag master branch (The semantic version 8.2.10 as well as the drupal "semantic" version 8.x-2.10) and push the new tags to origin. After tags are pushed, create release on drupal.org."

Issue #2923115 by daniel.bosen: Release 8.2.10 PR 2/3

---

modules/thunder_media/thunder_media.module

Issue #2923350: PHP Notice while adding image

---

modules/thunder_updater/updates.yml
thunder.install

Issue #2915666 by chr.fritsch, maosmurf: Upgrade path for paragraphs split module

---

docs/development.md
modules/thunder_media/config/optional/slick.optionset.thunder_gallery.yml
modules/thunder_media/config/update/thunder_media_update_8108.yml
modules/thunder_media/thunder_media.install
modules/thunder_taxonomy/thunder_taxonomy.install
modules/thunder_updater/templates/console/thunder_update_hook.php.twig
modules/thunder_updater/updates.yml
thunder.install

Issue #2926501 by daniel.bosen: Gallery images below the visible area do not get loaded

---

modules/thunder_paragraphs/modules/paragraph_split_text/js/plugins/splittext/plugin.js

fix paragraph-split bug when removing existing paragraph

---

.travis.yml
scripts/travis/05-setup-tests.sh

Issue #2930938 by chr.fritsch: Use older version of selenium/standalone-chrome

---

CHANGELOG.md
build-thunder.make

Create release branch from master, create two commits, one to bump version in build-thunder.make file and a second one to write the changelog. Merge back into master without squashing.

Issue #2926726 by daniel.bosen: Release 8.2.12 PR 2 / 3

---

docs/pull-screenshots-from-travis-ci.md
modules/thunder_media/tests/src/Functional/FileRemoveButtonTest.php
modules/thunder_media/tests/src/Functional/FilenameTransliterationTest.php
modules/thunder_updater/updates.yml
thunder.install

Fix update path

---

docs/development.md
modules/thunder_media/tests/src/Functional/FilenameTransliterationTest.php
scripts/travis/01-setup-environment.sh
scripts/travis/04-install-thunder.sh
scripts/travis/05-setup-tests.sh

Issue #2936777 by mtodor: Daily tests are failing with Drush 9

---

CHANGELOG.md
build-thunder.make

Create release branch from master, create two commits, one to bump version in build-thunder.make files and a second one to write the changelog. Merge back into master without squashing.

Issue #2937687 by daniel.bosen: Release 8.2.13 PR 2

---

CHANGELOG.md

Create branch from develop, cherry pick the changelog commit from master. Merge back to develop without squashing.

Issue #2937687 by daniel.bosen: Release 8.2.13

---

composer.json

Replace GPL-2.0+ by GPL-2.0-or-later

---

composer.json
config/install/content_lock.settings.yml
config/install/system.action.node_break_lock_action.yml
config/optional/views.view.content.yml
config/update/thunder__thunder_update_8113.yml

Content lock

---

modules/thunder_article/modules/thunder_riddle/config/optional/views.view.riddle_browser.yml
modules/thunder_media/config/optional/views.view.image_browser.yml
modules/thunder_media/config/optional/views.view.video_browser.yml

Issue #2945785 by mtodor: Incorrect langcode in configuration files

---

composer.json
drupal-org-core.make

update to drupal 8.4.5

---

modules/thunder_updater/thunder_updater.info.yml
tests/src/Functional/InstalledConfigurationTest.php
thunder.post_update.php
thunder.profile

Issue #2947051 by chr.fritsch, alexpott: Config Selector and Thunder Updater are required by Thunder

---

tests/src/Functional/InstalledConfigurationTest.php

Issue #2948617 by chr.fritsch: Enable config checks for more modules

---

scripts/travis/06-run-tests.sh
src/Tests/Installer/ThunderInstallerGermanTest.php

Issue #2948955 by chr.fritsch: Fix german installer test in D8.5

---

CHANGELOG.md
drupal-org-core.make

Release 8.2.15 PR3
